import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bessa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={"uk-section uk-section-primary"}
        data-uk-height-viewport={""}
      >
        <div className={"uk-container uk-container-xsmall"}>
          <h2>Bessa</h2>
          <p>The gay supper club</p>
        </div>
      </div>
    </>
  );
}
