import Head from "next/head";

import Navigation from "../components/Navigation";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bessa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div
        className={"uk-section"}
        data-uk-height-viewport={"offset-top: true"}
      >
        <div className={"uk-container uk-container-xsmall"}>
          <h1>Welcome to the gay supper club.</h1>
          <p>
            Meet other people in the community. Share your profile, your
            resources, and your number!
          </p>
        </div>
      </div>
    </>
  );
}
